select * from Teacher
select * from [Subject]
select * from Class
select * from Student
select * from [User]
select * from HeaderSchedule
select * from Shift
select * from DetailSchedule
select * from DetailClass
select * from Expertise